### ISSUE TITLE
Danger Notice For .notice class

### ISSUE THREAD

**Issue by mxritzdev** [tygzy/silicon#1]
**Is your feature request related to a problem? Please describe.**
As you know, I am using your small CSS Framework in a small app, and im trying to do a small error which shows up.

**Describe the solution you'd like**
Create a red version of the .notice to make errors possible to display

**Describe alternatives you've considered**
Also a specific style for errors would be nice

**Additional context**
![image](https://github.com/tygzy/silicon/assets/101179677/cb4c0ff4-9b8d-4df8-9d49-743dea575fe7)
Should look somethink like this ^^

**Comment by tygzy** [comment]
Will be adding this tonight or tomorrow with a new update.

**Comment by tygzy** [comment]
Update has been added and this style has been introduced.
